name: Build exe file

on:
  push:
    branches:
      - main
    paths:
      - "src/**/*.*"

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src
      - uses: actions/upload-artifact@v2
        with:
          name: app
          path: build
